tasks:
  # Install random utilities like `tree`
  - name: utils
    before: |
      sudo apt-get update
      sudo apt-get install -y tree

  # Install AWS CLI with auto-prompt enabled
  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      # Install AWS CLI
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

      # Create AWS config directory
      mkdir -p ~/.aws

      # Setup AWS credentials only if environment variables exist
      if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials

        echo "[default]" > ~/.aws/config
        echo "region=${AWS_DEFAULT_REGION:-ap-southeast-1}" >> ~/.aws/config
      else
        echo "AWS credentials not found in environment variables. Skipping configuration."
      fi

      # Verify AWS CLI installation and configuration
      aws --version
      echo "AWS CLI configuration:"
      cat ~/.aws/config || echo "No AWS config found"

 