tasks:
  # random utils
  - name: utils
    before: |
      sudp apt-get-install tree
  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

  - name:  aws-confgureation-aotu
    before: |
      echo "[default]" > ~/.aws/credentials
      echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
      echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials

      echo "[default]" > ~/.aws/config
      echo "region=${AWS_DEFAULT_REGION:-ap-southeast-1}" >> ~/.aws/config

    
