tasks:
  # Install random utilities like `tree`
  - name: utils
    before: |
      sudo apt-get update
      sudo apt-get install -y tree

  # Install AWS CLI with auto-prompt enabled
  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

 