#!/usr/bin/env bash
echo "== list 5 newest buckets"
# acccordding to the to the list number that been assinge there
aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[0:5] | .[] |  .Name'
echo "...q